### ISSUE TITLE
Request to sGTM Snowplow Client getting CORS blocked

### ISSUE THREAD

**Issue by rfortmann-ewolff** [snowplow/snowplow-gtm-server-side-client#23]
After having configured a Snowplow JS Tracker with the client-GTM templates (Tag + Variables) and having pointed the endpoint to the sGTM server as explained in this [chart](https://docs.snowplowanalytics.com/wp-content/uploads/sites/2/2021/11/gtmssoptions.png?w=1024), my POST events cannot come through as the console shows the following error:
`blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

Obviously I also imported and setup the Snowplow client in my server-side GTM as instructed [here].(https://docs.snowplowanalytics.com/docs/forwarding-events-to-destinations/forwarding-events/google-tag-manager-server-side/snowplow-client-for-gtm-ss/)

Did I forget something?

**Comment by rfortmann-ewolff** [comment]
We just tried GET requests, they seem to work but we are looking further into why POST requests will not work.

**Comment by adatzer** [comment]
Hello @rfortmann-ewolff !
This is expected behaviour when the request is indeed [cross-origin](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS), for example if you are sending requests from localhost.
Could that be the case?
Also, you mentioned you tried with GET requests, but i haven't managed to reproduce the behaviour you describe. Could you please provide more details about what you tried, so that we can construct a reproducible example?

**Comment by rfortmann-ewolff** [comment]
Hi @adatzer !
Our setup is built like this:
![sGTM drawio](https://user-images.githubusercontent.com/72810611/184350506-f530e42b-c886-4884-8f8f-8f7e935b539f.png)
In the Snowplow GTM client-side variable (Snowplow Template), there is the possibility of switching from POST to GET requests under the `dispatching method` options.

**Comment by adatzer** [comment]
Thank you for sharing @rfortmann-ewolff !

After looking at this more closely, i realized that my previous response to you was wrong! Actually, what you observe about the CORS issues for POST requests is _not_ expected under the _default_ settings. 

Below are my assumptions on your setup based on the information you shared, so that we can confirm on common ground:

1. You have setup the Snowplow GTM [v3 Variable](https://tagmanager.google.com/gallery/#/owners/snowplow/templates/snowplow-gtm-variable-template-v3), which is used for `Tracker Initialization` in the Snowplow GTM [v3 Tag](https://tagmanager.google.com/gallery/#/owners/snowplow/templates/snowplow-gtm-tag-template-v3) of your web container. (For clarity, let's below call them "gtm-web" Variable and Tag). This container is published and loaded on your website, say `www.company.com`. 
2. You have also deployed server-side tagging on a subdomain of your website, say `tm.company.com`.
3. You are using `tm.company.com` as the collector endpoint in your gtm-web Tag through the gtm-web Variable.
4. In your server-side container, which is also published, you have setup the Snowplow gtm-server-side [Client](https://github.com/snowplow/snowplow-gtm-server-side-client).
5. Assuming latest versions for all, but could you please also share the version of the Snowplow JavaScript Tracker you are loading through the gtm-web Variable/Tag?

If these are valid so far, then it is indeed unexpected that you are getting CORS errors for any POST or GET requests sent by the gtm-web Tag (i.e. the Snowplow JavaScript tracker under the hood). The reason is that the gtm-server-side Client ensures this by adding the required headers on its responses [through these lines here](https://github.com/snowplow/snowplow-gtm-server-side-client/blob/22f149ff13d39a1ad0185fbefa499273f5863438/template.tpl#L213-L216). This is expected for all GET, POST and OPTIONS(preflight) requests _that the Client claims_. 

Based on the above, together with 

 - the `No 'Access-Control-Allow-Origin' header is present` error message you shared and 
 - the fact that you are not getting CORS error on GET requests (which means that there is no protocol mismatch), 

the only way so far that i managed to replicate the issue was by a `POST Path` configuration mismatch between the gtm-web Tag and the gtm-server-side Client. Could that be the case? 

Could you please check this value in the gtm-web Variable:

![POST_Path_gtm_web_variable](https://user-images.githubusercontent.com/35838196/184450230-b3f7bdb3-d43a-4a70-83ea-f0ccc57284c9.png)

and this value in the gtm-server-side Client:

![POST_Path_gtm_ss_client](https://user-images.githubusercontent.com/35838196/184450260-7e274844-b0da-4ecb-961f-e7cd03c3a365.png)

Is this value still the default `/com.snowplowanalytics.snowplow/tp2` for both? Or are these `POST Path` values equal?

If yes, then this hypothesis is wrong! So then, could you please also share some information from the network tab in your browser's tools, more specifically the Request and Response headers for both the failing preflight and POST requests?

**Comment by rfortmann-ewolff** [comment]
HI @adatzer,

Thanks a lot for your help!
It seems to work! 🎉

Best regards!
